[package]
name = "polyfuse-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
polyfuse = "0.4"
thiserror = "1.0"
typed-builder = "0.9"
libc = "0.2"
